In [1]:
#program1: to calculate the total weekly energy from a list
daily_kwh = [500,700,220,600,300,200,500,400]
total_energy = sum(daily_kwh)
print("Total Energy used:",total_energy,"kwh")

Total Energy used: 3420 kwh

In [2]:
#program2 : Store building usage data
building_usage = {
    "CSE": 500,
    "Hostel":700
}
print("Hostel used:", building_usage["Hostel"], "kwh")

Hostel used: 700 kwh

In [3]:
#program3: a function to calculate electricity cost
def calculate_bill(kwh,rate_per_unit):
    return kwh * rate_per_unit
todays_bill = calculate_bill(500,8)
print("Today's estimated bill is Rs.", todays_bill)

Today's estimated bill is Rs. 4000

In [5]:
#program4: read a file line by line
with open("campus_energy.csv", "r") as file:
     for line in file.readlines():
          print(line.strip())

﻿Date,BUILDING,KWH_USE_PER_Hour_usuage,
05-10-2026,CSE,500,120
16-10-2026,HOSTEL,700,250
17-10-2026,CSE,220,110
18-10-2026,CIVIL,600,325
19-10-2026,MECH,300,210
20-10-2026,AIML,200,111
21-10-2026,AIDS,500,320
23-10-2026,BBA,400,250

In [16]:
import pandas as pd

# Load the dataset
df = pd.read_csv('campus_energy.csv')

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Display the column names
print("Column names:", df.columns.tolist())

# Display the first few rows
print("\nHere is the raw data:")
display(df.head())

# Calculate total usage per BUILDING
building_totals = df.groupby('BUILDING')['KWH_USE_PER_Hour_usuage'].sum()

print("\nTotal usage per Building:")
print(building_totals)

# Generate a statistical summary
print("\nStatistical Summary:")
display(df.describe())

Column names: ['Date', 'BUILDING', 'KWH_USE_PER_Hour_usuage', 'Unnamed: 3']

Here is the raw data:

         Date BUILDING  KWH_USE_PER_Hour_usuage  Unnamed: 3
0  05-10-2026      CSE                      500         120
1  16-10-2026   HOSTEL                      700         250
2  17-10-2026      CSE                      220         110
3  18-10-2026    CIVIL                      600         325
4  19-10-2026     MECH                      300         210

Total usage per Building:
BUILDING
AIDS      500
AIML      200
BBA       400
CIVIL     600
CSE       720
HOSTEL    700
MECH      300
Name: KWH_USE_PER_Hour_usuage, dtype: int64

Statistical Summary:

       KWH_USE_PER_Hour_usuage  Unnamed: 3
count                  8.00000    8.000000
mean                 427.50000  212.000000
std                  179.82134   89.756814
min                  200.00000  110.000000
25%                  280.00000  117.750000
50%                  450.00000  230.000000
75%                  525.00000  267.500000
max                  700.00000  325.000000

In [17]:
#Create the README.md file and write a message inside it
with open("README.md", "w") as file:
  file.write("#Smart Campus Energy Project\n")
  file.write("This repository contains my week 1 hands-on Python and pandas assignment.\n")
  file.write("Created by: [Nandini]")
print("README.md has been successfully created")

README.md has been successfully created